import Navbar from '@/components/shared/Navbar';
import { ThemeProvider } from '@/components/theme-provider';
import { getDictionary } from '@/configs/get-dictionary';
import { i18n, type Locale } from '@/configs/i18n-config';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '../favicon.ico',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: { lng: Locale };
}>) {
  const dictionary = await getDictionary(lng);
  return (
    <html lang={lng} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
